app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['uses' => 'PostController@index', 'as' => 'blog.index']);

Route::resource('blog', 'PostController', ['only' => ['show']]);

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'auth'], function () {

    Route::any('/', function () {
        return redirect()->route('admin.post.index');
    });

    Route::resource('post', 'PostController');
});

Route::auth();

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;
use Image;

/**
 * @property string image
 */
class Post extends Model
{
    protected $guarded = [];

    public function setImageAttribute($file)
    {
        if (is_string($file)) {
            $this->attributes['image'] = $file;
        } elseif ($file instanceof UploadedFile) {
            $image = Image::make($file);
            if($image->width() > $image->height()) {
                $image->resize(100, null, function ($constraint) {
                    $constraint->aspectRatio();
                });
            } else {
                $image->resize(null, 100, function ($constraint) {
                    $constraint->aspectRatio();
                });
            }

            $filename  = time() . '.' . $file->getClientOriginalName() . '.' . $file->getClientOriginalExtension();
            $image->save(public_path('images/' . $filename));
            $this->attributes['image'] = $filename;
        }
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\PostRequest;
use App\Post;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();
        return view('admin.list', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $post = new Post();
        return view('admin.create', compact('post'));
    }

    /**
     * Store a newly created resource in storage.
     *
     *
     * @param PostRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        $post = new Post($request->only(['slug', 'title', 'preview', 'text']));
        if ($request->hasFile('image')) {
            $post->image = $request->file('image');
        }
        $post->save();
        return redirect()->route('admin.post.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);

        if (!$post) {
            abort(404);
        }

        return view('admin.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param PostRequest $request
     * @param  int                 $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, $id)
    {
        /** @var Post $post */
        $post = Post::find($id);

        if (!$post) {
            abort(404);
        }
        if ($request->hasFile('image')) {
            $post->image = $request->file('image');
        }
        $post->update($request->only(['slug', 'title', 'preview', 'text']));

        return redirect()->route('admin.post.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Post::destroy($id);
        return redirect()->route('admin.post.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;

use App\Http\Requests;

class PostController extends Controller
{
    public function index()
    {
        $posts = Post::all();
        return view('blog.list', compact('posts'));
    }

    public function show($slug)
    {
        $post = Post::where('slug', $slug)->first();
        if (!$post) {
            abort(404);
        }
        return view('blog.post', compact('post'));
    }
}

resources/views/admin/create.blade.php
@extends('blog.layout')

@section('content')

    <form action="{{ route('admin.post.store') }}" method="post" enctype="multipart/form-data">

        @include('admin.form')

    </form>

@endsection

resources/views/admin/edit.blade.php
@extends('blog.layout')

@section('content')

    <form action="{{ route('admin.post.update', ['id' => $post->id]) }}" method="post" enctype="multipart/form-data">

        {{ method_field('PATCH') }}

        @include('admin.form')

    </form>

@endsection

resources/views/admin/form.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif


{{ csrf_field() }}

<div class="form-group">
    <label>slug</label>
    <input name="slug" type="text" class="form-control" id="" placeholder="slug" value="{{ $post->slug }}">
</div>

<div class="form-group">
    <label>title</label>
    <input name="title" type="text" class="form-control" id="" placeholder="title" value="{{ $post->title }}">
</div>

<div class="form-group">
    <label>preview</label>
    <textarea name="preview" class="form-control">{{ $post->preview }}</textarea>
</div>

<div class="form-group">
    <label>text</label>
    <textarea name="text" class="form-control">{{ $post->text }}</textarea>
</div>

<div class="form-group">
    <label>text</label>
    <input type="file" name="image">
</div>

<div class="form-group">
    <button class="btn btn-success" type="submit">save</button>
</div>

resources/views/admin/list.blade.php
@extends('blog.layout')

@section('content')

    <div class="row">
        @foreach($posts as $post)
            <div class="col-md-10">
                <div class="media">
                    <div class="media-left media-middle">
                        <a href="{{ route('blog.show', $post->slug) }}">
                            <img class="media-object" src="{{ asset('images/' . $post->image) }}" alt="">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">
                            <a href="{{ route('blog.show', $post->slug) }}">
                                {{ $post->title }}
                            </a>
                        </h4>
                        <span class="label label-primary">{{ $post->updated_at }}</span>
                        <p>
                            {{ $post->preview }}
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-2">

                <form class="form-inline" method="post" action="{{ route('admin.post.destroy', ['id' => $post->id]) }}">
                    {{ method_field('DELETE') }}
                    {{ csrf_field() }}
                    <a class="btn btn-warning" href="{{ route('admin.post.edit', ['id' => $post->id]) }}">
                        edit
                    </a>
                    <button type="submit" class="btn btn-danger">
                        delete
                    </button>
                </form>
            </div>
        @endforeach
    </div>

    <div class="row" style="margin-top: 30px;">
        <div class="col-md-12">
            <p>
                <a class="btn btn-success" href="{{ route('admin.post.create') }}">New post</a>
            </p>
        </div>
    </div>

@endsection

resources/views/blog/layout.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    <link rel="stylesheet" href="/css/all.css">
</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Blog</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="/admin">admin</a></li>
            </ul>
            @if(Auth::user())
                <div class="navbar-right">
                    <a class="navbar-brand pull-right" href="/logout">logout</a>
                </div>
            @endif
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="container">

    @yield('content', '')

</div><!-- /.container -->


<script src="/js/all.js"></script>
</body>
</html>

resources/views/blog/list.blade.php
@extends('blog.layout')

@section('content')

        @foreach($posts as $post)
            <div class="media">
                <div class="media-left media-middle">
                    <a href="{{ route('blog.show', $post->slug) }}">
                        <img class="media-object" src="{{ asset('images/' . $post->image) }}" alt="">
                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">
                        <a href="{{ route('blog.show', $post->slug) }}">
                            {{ $post->title }}
                        </a>
                    </h4>
                    <span class="label label-primary">{{ $post->updated_at }}</span>
                    <p>
                        {{ $post->preview }}
                    </p>
                </div>
            </div>
        @endforeach

@endsection

resources/views/blog/post.blade.php
@extends('blog.layout')

@section('content')

    <div class="media">
        <div class="media-left media-middle">
            <img class="media-object" src="{{ asset('images/' . $post->image) }}" alt="">
        </div>
        <div class="media-body">
            <h1 class="media-heading">
                {{ $post->title }}
            </h1>
            <span class="label label-primary">{{ $post->updated_at }}</span>
            <p>
                {{ $post->text }}
            </p>
        </div>
    </div>

    <a href="{{ route('blog.index') }}">
        all posts
    </a>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

    <!-- Styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

    <style>
        body {
            font-family: 'Lato';
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>
</head>
<body id="app-layout">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    Laravel
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('/home') }}">Home</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- JavaScripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js" integrity="sha384-I6F5OKECLVtK/BL+8iSLDEHowSAfUo76ZL9+kGAgTRdiByINKJaqTPH/QVNS1VDb" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    {{-- <script src="{{ elixir('js/app.js') }}"></script> --}}
</body>
</html>